os: linux
sudo: false
language: python
arch:
  -amd64
  -arm64

matrix:
  include:
    - python: 3.7
      env: TOXENV=py37
    - python: 3.7
      env: TOXENV=py37
install:
  - pip install tox
cache:
  - pip
script:
  - tox
