os: linux
sudo: false
language: python

matrix:
  include:
    - python: 3.8
      env: TOXENV=py38
      arch: amd64
    - python: 3.8
      env: TOXENV=py38
      arch: arm64
install:
  - pip install tox
cache:
  - pip
script:
  - tox
